### PR TITLE
fix single freq conflict and update state management

### LINKED ISSUE #14: single freq conflicts with current ui

### PR DESCRIPTION
**Pull request by rabi-siddique**
closes #14 

## UI

Before:
image

Now:
image

### CODE REVIEW

**Comment by dckc** [comment]
> Encountering this error when trying to create a portfolio:
> 
> ```
> ...
> 2025-04-30T10:10:23.242Z SwingSet: xsnap: v43: Error#7: key Object [Alleged: BLD brand] {} already registered in collection paymentToBrand
> ```

Ouch. That looks like a smartWallet bug:

 - https://github.com/Agoric/agoric-sdk/issues/11341

File: ui/src/components/PortfolioForm.tsx [hunk 1]
```diff
@@ -7,33 +7,41 @@ import { showError } from '../Utils';
 import { OfferArgsPortfolio } from '../interfaces/interfaces';
 import { type OfferSpec } from '@agoric/smart-wallet/src/offers.js';
 
-const chainOptions = ['Osmosis', 'Cosmos Hub'];
+const chainOptions = ['Osmosis', 'CosmosHub'];
```
Comment (dckc) [inline ui/src/components/PortfolioForm.tsx:10]: **Note** that our on-chain timer polling approach requires `icqEnabled`. cosmos hub mainnet doesn't have it enabled. I don't know whether the corresponding testnets do.

```js
const IcqEnabled = /** @type {const} */ ({
  omniflixhub: true,
  osmosis: true,
});
```
https://github.com/Agoric/agoric-sdk/blob/fb620c9645318f87ca749aa437e58e5970c19cef/packages/orchestration/src/chain-capabilities.js#L19-L22

File: ui/src/components/PortfolioForm.tsx [hunk 2]
```diff
@@ -141,57 +134,57 @@ export default function PortfolioForm() {
...
-            <label>Stake when tokens arrive:</label>
-            <input
-              type="checkbox"
-              checked={settings.stake || false}
-              onChange={() => toggleSetting('stake')}
-            />
+            <label>Polling Frequency:</label>
           </div>
           <div className="button-group">
             <button
```
Comment (dckc) [inline ui/src/components/PortfolioForm.tsx:140]: Since this is a choice of exclusive options, I **suggest** using radio buttons.

and `onChange` rather than `onClick`?

File: ui/src/components/PortfolioForm.tsx [hunk 3]
```diff
@@ -141,57 +134,57 @@ export default function PortfolioForm() {
...
           </div>
 
           <div className="setting-row">
-            <label>Restake when rewards accrue:</label>
+            <label>Stake when tokens arrive:</label>
             <input
               type="checkbox"
-              checked={settings.restake || false}
-              onChange={() => toggleSetting('restake')}
+              checked={!!config.onReceipt.length}
```
[the remark this answers is not in the document]
Comment (dckc) [reply ui/src/components/PortfolioForm.tsx:168]: My suggestion about radio buttons was intended for the frequency.

File: ui/src/components/PortfolioForm.tsx [hunk 4]
```diff
@@ -141,57 +134,57 @@ export default function PortfolioForm() {
...
-              type="button"
-              disabled={!settings.restake}
-              className={settings.restakeFrequency === 'weekly' ? 'active' : ''}
-              onClick={() => setFrequency('restake', 'weekly')}
-            >
-              Weekly
-            </button>
+
+          <div className="setting-row">
+            <label>Restake when rewards accrue:</label>
```
Comment (dckc) [inline ui/src/components/PortfolioForm.tsx:178]: To give the impression that we may add other features, I **suggest**:

When rewards accrue:
 - [ ] restake

File: ui/src/interfaces/interfaces.ts [hunk 5]
```diff
@@ -1,30 +1,11 @@
 import { makeAgoricWalletConnection } from '@agoric/web-components';
+import { CurrentWalletRecord } from '@agoric/smart-wallet/src/smartWallet.js';
+
 // XXX cross-package import
 import type { PortfolioConfig } from '../../../contract/typeGuards.js';
 
 export type Wallet = Awaited<ReturnType<typeof makeAgoricWalletConnection>>;
 
-// XXX  * @import {CurrentWalletRecord} from '@agoric/smart-wallet/src/smartWallet.js';
-export interface CurrentOffer {
```
Comment (dckc) [inline ui/src/interfaces/interfaces.ts:8]: :clap:

**Review by dckc — APPROVED** [review]
good stuff.

all comments are **suggestions** / **notes**; no **important** change requests
